version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: registerClients
    ports:
      - "5483:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springapp:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8090:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/registerClients
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: root
      volumes:
        - ./logs:/app/logs
volumes:
  postgres-data:

